---
name: Release

on:
  push:
    tags:
      - "v*"  # Push events to matching v*, i.e. vX.Y.Z

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Check-out"
        uses: actions/checkout@v1

      - name: "Generate changelog"
        id: generate-changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1
        with:
          onlyLastTag: "true"
          stripHeaders: "false"
          stripGeneratorNotice: "true"

      - name: "Create GitHub release"
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          draft: true
          prerelease: true
